# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alias_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='alias',
            name='description',
            field=models.CharField(default='name', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alias',
            name='name',
            field=models.CharField(default='name', max_length=50),
            preserve_default=False,
        ),
    ]
