# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20171006_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alias',
            name='name',
            field=models.CharField(max_length=501),
        ),
    ]
